apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-docker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-docker
  template:
    metadata:
      labels:
        app: hello-world-docker
    spec:
      containers:
      - name: hello-world-docker
        image: aldrickb/hello-world-docker:latest
        ports:
          - containerPort: 80