name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: aldrickb/hello-world-docker:latest

    - name: Install DigitalOcean CLI
      run: |
        curl -L https://github.com/digitalocean/doctl/releases/download/v1.78.0/doctl-linux-amd64.tar.gz | tar zxvf -
        chmod +x doctl
        sudo mv doctl /usr/local/bin/doctl

    - name: Login to DigitalOcean
      run: |
        doctl auth login --token ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    - name: Deploy to DigitalOcean App Platform
      run: |
        doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }} --format ID,Status